### ISSUE TITLE
Lands issue after lands update 

### ISSUE THREAD

**Issue by arturek1666** [Spazzinq/FlightControl#13]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Describe the bug** *(if not just an error)*
I am getting an error in console and plugin don't work (lands fault)
 ...
 
**Error** *(if there's an error, use gist to paste it)*
```
[09:40:52] [Server thread/ERROR]: Error occurred while enabling FlightControl v4 (Is it up to date?)
java.lang.NoClassDefFoundError: me/angeschossen/lands/api/landsaddons/LandsAddon
	at org.spazzinq.flightcontrol.hook.lands.Lands.<init>(Lands.java:35) ~[?:?]
	at org.spazzinq.flightcontrol.manager.HookManager.load(HookManager.java:94) ~[?:?]
	at org.spazzinq.flightcontrol.FlightControl.onEnable(FlightControl.java:120) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:291) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-80]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.ClassNotFoundException: me.angeschossen.lands.api.landsaddons.LandsAddon
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:150) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[patched_1.15.2.jar:git-Paper-80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	... 12 more
```
 ...
 
**Configuration** *(use gist to paste)*
No configuration as I removed all files for fresh install
 ...
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
 ...
 
**Server Version** *(e.g. Spigot 1.8.8)*
paper 1.15.2
 ...

**Comment by Spazzinq** [comment]
You're using version 4! You have to use the beta version I gave you!
