### ISSUE TITLE
CombatLogX NSME

### ISSUE THREAD

**Issue by thiagogebrimm** [Spazzinq/FlightControl#185]
[17:40:24 WARN]: [FlightControl] Task #322324 for FlightControl v4.10.0 generated an exception
java.lang.NoSuchMethodError: 'com.github.sirblobman.combatlogx.api.ICombatManager com.github.sirblobman.combatlogx.api.ICombatLogX.getCombatManager()'
        at org.spazzinq.flightcontrol.check.combat.CombatLogX11Check.check(CombatLogX11Check.java:38) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.util.CheckUtil.evaluate(CheckUtil.java:54) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.manager.StatusManager.check(StatusManager.java:99) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.manager.StatusManager.checkDisable(StatusManager.java:85) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.manager.StatusManager.checkDisable(StatusManager.java:74) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.manager.FlightManager.check(FlightManager.java:69) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.manager.FlightManager.check(FlightManager.java:58) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.EventListener$1.run(EventListener.java:67) ~[FlightControl.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1825]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Spazzinq** [comment]
What version of CombatLogX are you using?

**Comment by Spazzinq** [comment]
No response, plugin likely wasn't enabled

**Comment by thiagogebrimm** [comment]
![image](https://user-images.githubusercontent.com/75040244/201537738-56a48350-3370-4f66-8ef4-360902c2586f.png)
