### ISSUE TITLE
CombatLogX erro in latest dev version - 4.10.1-BETA

### ISSUE THREAD

**Issue by thiagogebrimm** [Spazzinq/FlightControl#204]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Discord Tag** *(so I can notify you if I need more information or if an issue is fixed)*
Thiago Gebrim#7204
 ...

**Describe the bug** *(if not just an error)*
```
**Error** *(if there's an error, use gist to paste it)*
[14:25:56 ERROR]: Could not pass event PlayerTeleportEvent to FlightControl v4.10.0
java.lang.NoSuchMethodError: 'com.github.sirblobman.combatlogx.api.ICombatManager com.github.sirblobman.combatlogx.api.ICombatLogX.getCombatManager()'
        at org.spazzinq.flightcontrol.check.combat.CombatLogX11Check.check(CombatLogX11Check.java:38) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.util.CheckUtil.evaluate(CheckUtil.java:54) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.manager.StatusManager.check(StatusManager.java:99) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.manager.StatusManager.checkDisable(StatusManager.java:85) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.manager.StatusManager.checkDisable(StatusManager.java:74) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.manager.FlightManager.check(FlightManager.java:69) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.manager.FlightManager.check(FlightManager.java:58) ~[FlightControl.jar:?]
        at org.spazzinq.flightcontrol.EventListener.onTP(EventListener.java:103) ~[FlightControl.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1861]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1283) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1190) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1185) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftEntity.teleport(CraftEntity.java:553) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$1.run(MVPlayerListener.java:326) ~[Multiverse-Core-4.3.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1498) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1422) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[purpur-1.19.3.jar:git-Purpur-1861]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
 ...
 
**Configuration** *(use gist to paste)*
 ...
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
 ...
 
**Server Version** *(e.g. Spigot 1.8.8)*
1.19.3
 ...

**Comment by Spazzinq** [comment]
What version of CombatLogX is this?

**Comment by Spazzinq** [comment]
Nevermind, found the issue. SirBlobman forgot to update the target API.
