### ISSUE TITLE
Error Enabling Plugin

### ISSUE THREAD

**Issue by Loottzy** [Spazzinq/FlightControl#347]
[18:15:32] [Server thread/INFO]: [FlightControl] Enabling FlightControl v4.9.21
[18:15:32] [Server thread/ERROR]: Error occurred while enabling FlightControl v4.9.21 (Is it up to date?)
java.lang.NoSuchFieldError: CLOUD
	at org.spazzinq.flightcontrol.multiversion.legacy.Particle8.<init>(Particle8.java:32) ~[FlightControl.jar:?]
	at org.spazzinq.flightcontrol.FlightControl.registerManagers(FlightControl.java:122) ~[FlightControl.jar:?]
	at org.spazzinq.flightcontrol.FlightControl.onEnable(FlightControl.java:80) ~[FlightControl.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:15:32] [Server thread/INFO]: [FlightControl] Disabling FlightControl v4.9.21
[18:15:32] [Server thread/ERROR]: Error occurred while disabling FlightControl v4.9.21
java.lang.NullPointerException: Cannot invoke "org.spazzinq.flightcontrol.manager.PlayerManager.savePlayerData()" because "this.playerManager" is null
	at org.spazzinq.flightcontrol.FlightControl.onDisable(FlightControl.java:95) ~[FlightControl.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:194) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Spazzinq** [comment]
Hi, you're trying to run an unsupported version of FlightControl. Please download the latest BETA from here: https://github.com/Spazzinq/FlightControl/releases
