### ISSUE TITLE
NPE with PremiumVanish

### ISSUE THREAD

**Issue by stonegray** [Spazzinq/FlightControl#66]
**Describe the bug** *(if not just an error)*
 FlightControl spams exceptions into console.
 
- FlightControl v4.7.13-BETA
- PremiumVanish 2.6.2
- Tunity 1.16.4
 
**Error** *(if there's an error, use gist to paste it)*
```
[01:08:11 WARN]: [FlightControl] Task #612686 for FlightControl v4.7.13-BETA generated an exception
java.lang.NullPointerException: null
        at org.spazzinq.flightcontrol.check.bypasstrail.vanish.PremiumSuperVanishCheck.check(PremiumSuperVanishCheck.java:32) ~[?:?]
        at org.spazzinq.flightcontrol.util.CheckUtil.evaluate(CheckUtil.java:54) ~[?:?]
        at org.spazzinq.flightcontrol.util.CheckUtil.evaluate(CheckUtil.java:65) ~[?:?]
        at org.spazzinq.flightcontrol.manager.FlightManager.check(FlightManager.java:63) ~[?:?]
        at org.spazzinq.flightcontrol.manager.FlightManager.check(FlightManager.java:58) ~[?:?]
        at org.spazzinq.flightcontrol.object.FlightPlayer$1$1.run(FlightPlayer.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1351) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
 

**Configuration** *(use gist to paste)*
Using default configuration.
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
Error does not appear to be related to any single player or action.
 
**Server Version** *(e.g. Spigot 1.8.8)*
 Server version is Tunity 1.16.4

**Comment by Spazzinq** [comment]
**SELF-NOTE**: This seems to be a similar issue reported by a Discord user. The relevant log is here: https://pastebin.com/A2XRKswW

Proposed Solution: Simple null check on the delayed task.

**Comment by Spazzinq** [comment]
Please try this [release](https://github.com/Spazzinq/FlightControl/releases/tag/4.7.19-BETA).

**Comment by stonegray** [comment]
This resolves the issue and causes some others, I'll open a new ticket for them.

**Comment by Spazzinq** [comment]
> This resolves the issue and causes some others, I'll open a new ticket for them.

Apologies, why don't you try [this release](https://github.com/Spazzinq/FlightControl/releases/tag/4.7.20-BETA). I fixed a critical mistake.
